install.sh 및 etc/install 스크립트 수정
- dotfiles 복사 방식에서 링크 방식으로 변경
- etc/install에서 git, curl, wget 존재 여부 체크 로직 개선
- oh-my-zsh 설치 스크립트에서 ZSH_CUSTOM 변수 설정 추가
- minor formatting 개선

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -13,13 +13,21 @@ cat <<EOF
 EOF
 
 # Check minimal dependencies
-if ! command -v git &> /dev/null; then echo "ERROR: git not found. (Try $APT install git)"; exit; fi
-if ! command -v curl &> /dev/null; then echo "ERROR: curl not found. (Try $APT install curl)"; exit; fi
-if ! command -v wget &> /dev/null; then echo "ERROR: wget not found. (Try $APT install wget)"; exit; fi
+if ! command -v git &>/dev/null; then
+    echo "ERROR: git not found. (Try $APT install git)"
+    exit
+fi
+if ! command -v curl &>/dev/null; then
+    echo "ERROR: curl not found. (Try $APT install curl)"
+    exit
+fi
+if ! command -v wget &>/dev/null; then
+    echo "ERROR: wget not found. (Try $APT install wget)"
+    exit
+fi
 
 GIT_REPO="https://github.com/mino-park7/dotfiles.git"
 GIT_BRANCH="main"
-
 
 set -e
 
@@ -29,7 +37,7 @@ cd ~
 # Check if the dotfiles directory already exists
 if [ -d ~/.dotfiles ]; then
     echo "~/.dotfiles directory already exists. Updating..."
-    cd ~/.dotfiles && git pull
+    cd ~/.dotfiles && git stash && git pull && git stash pop
 else
     git clone --depth 1 --branch $GIT_BRANCH $GIT_REPO ~/.dotfiles
 fi
